# Generated by Django 3.2.7 on 2021-12-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_adminscheduledtask'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminscheduledtask',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_name', to='accounts.profile'),
        ),
    ]
