# Generated by Django 3.2.7 on 2021-12-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211214_1001'),
        ('administration', '0002_alter_adminscheduledtask_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminScheduledConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(null=True)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_name', to='accounts.profile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='AdminScheduledTask',
        ),
    ]
