# Generated by Django 3.2.7 on 2021-12-14 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211214_1001'),
        ('administration', '0003_auto_20211214_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminscheduledconsultation',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminscheduledconsultation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.profile'),
        ),
    ]
