# Generated by Django 3.2.7 on 2021-12-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20211214_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminscheduledconsultation',
            name='approved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
