# Generated by Django 3.2.7 on 2021-12-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_adminscheduledconsultation_approved_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminscheduledconsultation',
            name='approved_time',
        ),
    ]
