# Generated by Django 3.2.7 on 2022-05-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_program_code'),
        ('administration', '0007_auto_20220522_1404'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminscheduledconsultation',
            unique_together={('managed_by', 'client')},
        ),
    ]
