# Generated by Django 3.2.7 on 2022-05-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_program_code'),
        ('administration', '0009_alter_adminscheduledconsultation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminscheduledconsultation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.profile'),
        ),
    ]
