# Generated by Django 3.2.7 on 2021-12-09 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RIASEC_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('slug', models.SlugField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=100)),
            ],
            options={
                'verbose_name': 'RIASEC Test',
                'verbose_name_plural': 'RIASEC Tests',
            },
        ),
        migrations.CreateModel(
            name='Riasec_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realistic', models.FloatField(default=0)),
                ('investigative', models.FloatField(default=0)),
                ('artistic', models.FloatField(default=0)),
                ('social', models.FloatField(default=0)),
                ('enterprising', models.FloatField(default=0)),
                ('conventional', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RIASEC Result',
                'verbose_name_plural': 'RIASEC Results',
            },
        ),
    ]
