# Generated by Django 3.2.7 on 2022-04-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0004_alter_riasec_test_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('realistic', models.FloatField(default=0)),
                ('investigative', models.FloatField(default=0)),
                ('artistic', models.FloatField(default=0)),
                ('social', models.FloatField(default=0)),
                ('enterprising', models.FloatField(default=0)),
                ('conventional', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='riasec_result',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riasec.cluster'),
        ),
    ]
