# Generated by Django 3.2.7 on 2022-05-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0009_alter_question_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, choices=[('realistic', 'Realistic'), ('investigative', 'Investigative'), ('artistic', 'Artistic'), ('social', 'Social'), ('enterprising', 'Enterprising'), ('conventional', 'Conventional')], max_length=16, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riasec.program')),
            ],
        ),
    ]
