# Generated by Django 3.2.7 on 2022-05-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0012_auto_20220501_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='riasec.department'),
        ),
    ]
