# Generated by Django 3.2.7 on 2022-05-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220504_1942'),
        ('riasec', '0013_program_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='department',
        ),
        migrations.AlterField(
            model_name='offeredprogram',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.program'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
