# Generated by Django 3.2.7 on 2022-05-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0014_auto_20220504_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='result',
            name='prediction',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
