# Generated by Django 3.2.7 on 2021-11-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('EXT', 'Extroversion'), ('EST', 'Neurotic'), ('AGR', 'Agreeable'), ('CSN', 'Conscientious'), ('OPN', 'Openness')], max_length=100)),
            ],
        ),
    ]
