# Generated by Django 3.2.7 on 2021-11-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalityTest', '0003_result_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=10)),
                ('extroversion', models.FloatField(default=0)),
                ('neurotic', models.FloatField(default=0)),
                ('agreeable', models.FloatField(default=0)),
                ('conscientious', models.FloatField(default=0)),
                ('openness', models.FloatField(default=0)),
            ],
        ),
    ]
