# Generated by Django 3.2.7 on 2021-12-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalityTest', '0005_questionnaire_slug'),
        ('personalityTest', '0007_alter_result_prediction'),
    ]

    operations = [
    ]
