# Generated by Django 3.2.7 on 2021-12-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalityTest', '0008_merge_20211203_1805'),
        ('personalityTest', '0008_merge_20211203_2002'),
    ]

    operations = [
    ]
