# Generated by Django 3.2.7 on 2021-12-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalityTest', '0009_merge_20211204_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='key',
            field=models.CharField(blank=True, choices=[('1', 'Positive'), ('2', 'Negative')], max_length=10, null=True),
        ),
    ]
