# Generated by Django 3.2.7 on 2021-12-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalityTest', '0011_auto_20211207_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Questionnaires'},
        ),
    ]
