# Generated by Django 3.2.7 on 2022-04-28 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalityTest', '0015_alter_cluster_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('EXT', 'Extroversion'), ('EST', 'Neurotic'), ('AGR', 'Agreeable'), ('CSN', 'Conscientious'), ('OPN', 'Openness')], max_length=32, null=True)),
                ('key', models.CharField(blank=True, choices=[('1', 'Positive'), ('0', 'Negative')], max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('EXT', 'Extroversion'), ('EST', 'Neurotic'), ('AGR', 'Agreeable'), ('CSN', 'Conscientious'), ('OPN', 'Openness')], max_length=100)),
                ('key', models.CharField(blank=True, choices=[('1', 'Positive'), ('0', 'Negative')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
            },
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.AlterField(
            model_name='result',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalityTest.cluster'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalityTest.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
