# Generated by Django 3.2.7 on 2022-05-01 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0013_program_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalityTest', '0018_auto_20220428_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offeredCarrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='riasec.offeredprogram')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
