# Generated by Django 3.2.7 on 2022-05-01 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riasec', '0013_program_department'),
        ('personalityTest', '0020_alter_recommendedcareer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendedCareer',
            new_name='RecommendedProgram',
        ),
        migrations.RenameField(
            model_name='recommendedprogram',
            old_name='offeredCarrer',
            new_name='offeredProgram',
        ),
    ]
