# Generated by Django 3.2.7 on 2021-12-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
