# Generated by Django 3.2.7 on 2021-12-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='profile',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
