# Generated by Django 3.2.7 on 2021-12-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211213_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
