# Generated by Django 3.2.7 on 2021-12-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='set_date',
            field=models.DateTimeField(null=True),
        ),
    ]
