# Generated by Django 3.2.7 on 2021-12-13 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211213_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='managed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
