# Generated by Django 3.2.7 on 2021-12-14 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_managed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='set_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.CreateModel(
            name='AdminScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(null=True)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_name', to='accounts.profile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.profile')),
            ],
        ),
    ]
