# Generated by Django 3.2.7 on 2021-12-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211214_0909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminScheduledTask',
        ),
    ]
