# Generated by Django 3.2.7 on 2021-12-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211214_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_approved',
            new_name='is_assigned',
        ),
    ]
