# Generated by Django 3.2.7 on 2022-03-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220224_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('IBED', 'Integrated Basic Education (Preschool to SHS)'), ('College', 'College Department')], max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(choices=[('Grade', 'Grade School'), ('Junior', 'Junior Highschool'), ('Senior', 'Senior Highschool'), ('BSA', 'BS in Accountancy'), ('BSBA', 'BS in Business Administration'), ('BSMA', 'BS in Management Accounting'), ('BSC', 'BS in Criminology'), ('BSCE', 'BS in Civil Engineering'), ('BSE', 'Bachelor in Secondary Education'), ('BEE', 'Bachelor in Elementary Education'), ('BSIT', 'BS in Information Technology'), ('BSP', 'BS in Psychology'), ('BSSW', 'BS in Social Work'), ('BSMT', 'BS in Medical Technology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12'), ('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year')], max_length=50),
        ),
    ]
