# Generated by Django 3.2.7 on 2022-04-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220412_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contacts',
            new_name='contactNumber',
        ),
    ]
