# Generated by Django 3.2.7 on 2022-05-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220504_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='CollegeDepartment',
        ),
        migrations.AddField(
            model_name='profile',
            name='academictrack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.academictrack'),
        ),
    ]
