# Generated by Django 3.2.7 on 2022-05-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20220505_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='education',
            new_name='educationlevel',
        ),
    ]
