# Generated by Django 3.2.7 on 2022-05-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_education_profile_educationlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academictrack',
            old_name='label',
            new_name='name',
        ),
        migrations.AddField(
            model_name='academictrack',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
