# Generated by Django 3.2.7 on 2022-05-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20220505_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedepartment',
            name='educationlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.educationlevel'),
        ),
    ]
