# Generated by Django 3.2.7 on 2022-05-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_collegedepartment_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='educationlevel',
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.CharField(blank=True, choices=[('COLLEGE', 'COLLEGE'), ('IBED', 'Integrated Basic Education Department')], max_length=64, null=True),
        ),
    ]
