# Generated by Django 3.2.7 on 2022-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20220505_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='academictrack',
        ),
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.CharField(blank=True, choices=[('COLLEGE', 'College'), ('IBED', 'Integrated Basic Education Department')], max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='AcademicTrack',
        ),
    ]
