# Generated by Django 3.2.7 on 2022-05-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20220505_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='educationallevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.educationlevel'),
        ),
    ]
