# Generated by Django 3.2.7 on 2022-05-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_year_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='educationallevel',
            new_name='educationlevel',
        ),
    ]
