# Generated by Django 3.2.7 on 2022-05-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_rename_educationallevel_year_educationlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='accounts.department'),
        ),
    ]
