# Generated by Django 3.2.7 on 2022-05-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_profile_is_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='test_completed',
            new_name='last_test_taken',
        ),
    ]
