# Generated by Django 3.2.7 on 2022-05-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_rename_test_completed_profile_last_test_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
