# Generated by Django 3.2.7 on 2022-05-24 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_program_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='level',
        ),
        migrations.AddField(
            model_name='department',
            name='educationlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.educationlevel'),
        ),
    ]
