# Generated by Django 3.2.7 on 2022-10-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_rename_gender_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.program'),
        ),
    ]
