# Generated by Django 3.2.7 on 2022-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_profile_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
