# Generated by Django 3.2.7 on 2022-11-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_educationlevel_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationlevel',
            name='name2',
        ),
    ]
