# Generated by Django 3.2.7 on 2022-12-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iqtest', '0001_initial'),
    ]

    operations = [
    ]
