# Generated by Django 3.2.7 on 2023-01-01 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqtest', '0004_remove_result_label'),
    ]

    operations = [

    ]
