# Generated by Django 3.2.7 on 2023-01-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqtest', '0005_alter_question_question'),
    ]

    operations = [
    ]
