# Generated by Django 3.2.7 on 2023-01-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqtest', '0007_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_answer',
            field=models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect')], default='incorrect', max_length=32),
        ),
    ]
