# Generated by Django 3.2.7 on 2023-01-22 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_remove_educationlevel_name2'),
        ('iqtest', '0010_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iq_answer_user', to='accounts.profile'),
        ),
    ]
